export const blogPosts = [
  {
    slug: "top-10-kdramas-2026",
    title: "Top 10 KDramas to Watch in 2026",
    excerpt: "From action-packed thrillers to heartwarming romances, here are the must-watch Korean dramas dominating screens this year.",
    image: "https://images.unsplash.com/photo-1616279969965-b21f1e3aa48d?w=800",
    date: "2026-06-01",
    content: [
      { type: "text", text: "Korean dramas continue to capture hearts worldwide, and 2026 has been an incredible year for the genre. Whether you love action, romance, comedy, or thrillers, there's something for everyone." },
      { type: "heading", text: "1. Squid Game" },
      { type: "text", text: "The global phenomenon continues to dominate conversations with its intense survival storyline and unforgettable characters." },
      { type: "drama_link", text: "2. Weak Hero", id: "200709" },
      { type: "text", text: "A gripping story about a gifted student who must confront violence he never expected to face, packed with emotional depth and action." },
      { type: "drama_link", text: "3. Bloodhounds", id: "127529" },
      { type: "text", text: "Two young boxers team up to fight against ruthless loan sharks in this action-packed underdog story." },
      { type: "heading", text: "4. Running Man" },
      { type: "text", text: "The legendary variety show continues to entertain with hilarious challenges and celebrity guests." },
      { type: "heading", text: "5. The WONDERfools" },
      { type: "text", text: "A heartfelt comedy-drama about friendship and chasing dreams against all odds." },
      { type: "text", text: "Browse our KDrama section to explore detailed ratings, cast info, and trailers for each show!" },
    ],
  },
  {
    slug: "best-cdramas-beginners",
    title: "Best CDramas for Beginners: Where to Start",
    excerpt: "New to Chinese dramas? These fan-favorite CDramas are the perfect entry point into this captivating world.",
    image: "https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=800",
    date: "2026-05-28",
    content: [
      { type: "text", text: "Chinese dramas have exploded in popularity worldwide thanks to their stunning visuals, intricate storylines, and talented casts. If you're just getting started, here's where to begin." },
      { type: "heading", text: "1. Soul Land" },
      { type: "text", text: "A fantasy epic following a young hero's journey through a world of martial arts and spirits — perfect for fans of action and adventure." },
      { type: "heading", text: "2. Renegade Immortal" },
      { type: "text", text: "An immersive fantasy drama with breathtaking visual effects and a compelling protagonist's rise to power." },
      { type: "heading", text: "3. The Ferry Man" },
      { type: "text", text: "A mystery thriller that keeps you guessing until the very end, with strong performances from its lead cast." },
      { type: "text", text: "Check out our CDrama section for full cast details, ratings, and where each series ranks among fan favorites." },
    ],
  },
  {
    slug: "kdramas-like-squid-game",
    title: "If You Loved Squid Game, Watch These Next",
    excerpt: "Craving more intense, high-stakes drama after Squid Game? Here are similar shows that will keep you on the edge of your seat.",
    image: "https://images.unsplash.com/photo-1582213782179-e0d53f98f2ca?w=800",
    date: "2026-05-20",
    content: [
      { type: "text", text: "Squid Game redefined what international audiences expect from Korean dramas — intense psychological tension, social commentary, and unforgettable characters." },
      { type: "drama_link", text: "1. Bloodhounds", id: "127529" },
      { type: "text", text: "Like Squid Game, this drama explores desperation and survival, following two boxers caught in a dangerous underworld of debt collection." },
      { type: "drama_link", text: "2. Weak Hero", id: "200709" },
      { type: "text", text: "Themes of violence, power dynamics, and moral struggle make this a strong follow-up for Squid Game fans." },
      { type: "text", text: "Explore our Trending KDramas section on the homepage to discover more shows with similar themes and high ratings!" },
    ],
  },
];