export const blogPosts = [
  {
    slug: "top-10-kdramas-2026",
    title: "Top 10 KDramas to Watch in 2026",
    excerpt: "From action-packed thrillers to heartwarming romances, here are the must-watch Korean dramas dominating screens this year.",
    image: "https://images.unsplash.com/photo-1616279969965-b21f1e3aa48d?w=800",
    date: "2026-06-01",
    content: [
      { type: "text", text: "Korean dramas continue to capture hearts worldwide, and 2026 has been an incredible year for the genre. From gritty survival thrillers to emotionally rich coming-of-age stories, there's something here for every kind of viewer. We've rounded up ten titles currently dominating conversations among KDrama fans." },
      { type: "drama_link", text: "1. Squid Game", id: "93740" },
      { type: "text", text: "The global phenomenon that redefined what a Korean drama could be internationally. Its brutal survival games are a backdrop for sharp commentary on class, debt, and desperation, and the characters remain some of the most memorable in recent television." },
      { type: "drama_link", text: "2. Weak Hero", id: "200709" },
      { type: "text", text: "A gripping story about a gifted but quiet student who is forced to confront violence he never expected to face. The series balances brutal school-violence sequences with genuine emotional depth, making it one of the standout action dramas of the year." },
      { type: "drama_link", text: "3. Bloodhounds", id: "127529" },
      { type: "text", text: "Two young boxers get pulled into the dangerous underworld of loan sharks in this underdog story that mixes raw fight choreography with genuine heart. It's an easy recommendation for fans of high-stakes action with real emotional stakes." },
      { type: "heading", text: "4. Running Man" },
      { type: "text", text: "The legendary variety show continues to entertain after more than a decade on air, bringing hilarious physical challenges and a rotating cast of celebrity guests. It remains one of the most accessible entry points into Korean entertainment for newcomers." },
      { type: "heading", text: "5. The WONDERfools" },
      { type: "text", text: "A heartfelt comedy-drama about friendship, ambition, and chasing dreams against impossible odds. Lighter in tone than many of the other entries on this list, it's a perfect palate cleanser between heavier watches." },
      { type: "text", text: "Whether you're new to KDramas or a longtime fan, this list offers a strong mix of tone and genre. For full cast details, ratings, and trailers, browse our KDrama section to dig deeper into any of these picks." },
    ],
  },
  {
    slug: "best-cdramas-beginners",
    title: "Best CDramas for Beginners: Where to Start",
    excerpt: "New to Chinese dramas? These fan-favorite CDramas are the perfect entry point into this captivating world.",
    image: "https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=800",
    date: "2026-05-28",
    content: [
      { type: "text", text: "Chinese dramas have exploded in popularity worldwide thanks to their stunning visuals, intricate storylines, and devoted casts. They can also feel intimidating to newcomers given how long some series run, often forty episodes or more. Here's where to start if you're just getting into the genre." },
      { type: "drama_link", text: "1. A Dream Within a Dream", id: "253193" },
      { type: "text", text: "A fantasy romance with a clever meta twist — the heroine is pulled into a scripted world where every choice she makes is bound by fate. It's a strong example of how inventive CDrama storytelling has become in recent years." },
      { type: "heading", text: "2. Soul Land" },
      { type: "text", text: "A fantasy epic following a young hero's journey through a world of martial arts and spirits, perfect for fans of action and adventure who want something visually ambitious." },
      { type: "heading", text: "3. The Ferry Man" },
      { type: "text", text: "A mystery thriller that keeps you guessing until the very end, anchored by strong performances from its lead cast. A good pick if you want something tighter and more plot-driven than the typical romance-heavy CDrama." },
      { type: "text", text: "CDramas often reward patience with rich world-building and slow-burn character development. Start with something shorter if you're easing in, then work your way up to the longer historical epics once you're hooked. Check out our CDrama section for full cast details, ratings, and where each series ranks among fan favorites." },
    ],
  },
  {
    slug: "kdramas-like-squid-game",
    title: "If You Loved Squid Game, Watch These Next",
    excerpt: "Craving more intense, high-stakes drama after Squid Game? Here are similar shows that will keep you on the edge of your seat.",
    image: "https://images.unsplash.com/photo-1582213782179-e0d53f98f2ca?w=800",
    date: "2026-05-20",
    content: [
      { type: "text", text: "Squid Game redefined what international audiences expect from Korean dramas, blending intense psychological tension with sharp social commentary and characters you can't stop thinking about. If you finished it and immediately wanted more, these picks share its DNA." },
      { type: "drama_link", text: "1. Bloodhounds", id: "127529" },
      { type: "text", text: "Like Squid Game, this drama explores desperation and survival, following two young boxers caught in a dangerous underworld of debt collection. The stakes feel personal rather than abstract, which is part of what makes it work." },
      { type: "drama_link", text: "2. Weak Hero", id: "200709" },
      { type: "text", text: "Themes of violence, power dynamics, and moral compromise make this a strong follow-up for Squid Game fans, particularly anyone drawn to the show's exploration of what ordinary people will do under pressure." },
      { type: "heading", text: "What Made Squid Game Work" },
      { type: "text", text: "It wasn't really about the games themselves — it was the human stories underneath the spectacle. Each contestant carried real desperation, and the show never let you forget the cost of survival. The dramas above carry that same thread in different settings." },
      { type: "text", text: "Explore our Trending KDramas section on the homepage to discover more shows with similarly high stakes and strong ratings." },
    ],
  },
];